import random

# A list of all possible candy-themed attacks
ATTACK_LIST = [
    {"attack_name": "Sugar Rush", "base_damage": 2},
    {"attack_name": "Caramel Whip", "base_damage": 3},
    {"attack_name": "Gummy Bite", "base_damage": 2},
    {"attack_name": "Chocolate Blast", "base_damage": 4},
    {"attack_name": "Lollipop Smack", "base_damage": 3},
    {"attack_name": "Frosting Spray", "base_damage": 2},
    {"attack_name": "Jawbreaker Hit", "base_damage": 5},
    {"attack_name": "Sour Splash", "base_damage": 3},
    {"attack_name": "Syrup Splash", "base_damage": 3},
    {"attack_name": "Sprinkle Storm", "base_damage": 3},
    {"attack_name": "Choco Blast", "base_damage": 4},
    {"attack_name": "Marshmallow Slam", "base_damage": 3},
    {"attack_name": "Gummy Punch", "base_damage": 2},
    {"attack_name": "Caramel Wave", "base_damage": 3},
    {"attack_name": "Nougat Strike", "base_damage": 3},
    {"attack_name": "Fudge Bomb", "base_damage": 4},
    {"attack_name": "Licorice Lash", "base_damage": 2},
    {"attack_name": "Jelly Jab", "base_damage": 2},
    {"attack_name": "Bonbon Barrage", "base_damage": 3},
    {"attack_name": "Truffle Tackle", "base_damage": 3},
    {"attack_name": "Sugar Rush", "base_damage": 2},
    {"attack_name": "Candy Crush", "base_damage": 4},
    {"attack_name": "Mochi Missile", "base_damage": 3},
    {"attack_name": "Taffy Twist", "base_damage": 2},
    {"attack_name": "Jelli Jolt", "base_damage": 3},
    {"attack_name": "Frost Flurry", "base_damage": 2},
    {"attack_name": "Cinna Swipe", "base_damage": 2},
    {"attack_name": "Mallow Mash", "base_damage": 3},
    {"attack_name": "Sour Shock", "base_damage": 3},
    {"attack_name": "Twizzle Whip", "base_damage": 2},
    {"attack_name": "Crumble Crash", "base_damage": 3},
    {"attack_name": "Snicker Snap", "base_damage": 2},
    {"attack_name": "Cocoa Cannon", "base_damage": 4},
    {"attack_name": "Meringue Missile", "base_damage": 3},
    {"attack_name": "Gumdrop Grenade", "base_damage": 4},
    {"attack_name": "S'more Smash", "base_damage": 3},
    {"attack_name": "Frostbite", "base_damage": 2},
    {"attack_name": "Pecan Pummel", "base_damage": 3},
    {"attack_name": "Maple Maul", "base_damage": 3},
    {"attack_name": "Crisp Crunch", "base_damage": 2},
    {"attack_name": "Cane Strike", "base_damage": 3},
    {"attack_name": "Brittle Bash", "base_damage": 3},
    {"attack_name": "Fudge Fling", "base_damage": 3},
    {"attack_name": "Mochi Maul", "base_damage": 3},
    {"attack_name": "Puffer Pop", "base_damage": 2},
    {"attack_name": "Cinna Strike", "base_damage": 2},
    {"attack_name": "Syrup Shot", "base_damage": 2},
    {"attack_name": "Glaze Glint", "base_damage": 2},
    {"attack_name": "Mallow Maul", "base_damage": 3},
    {"attack_name": "Tart Toss", "base_damage": 2},
    {"attack_name": "Crumble Cut", "base_damage": 3},
    {"attack_name": "Jelly Jolt", "base_damage": 2},
    {"attack_name": "Nougat Nudge", "base_damage": 2},
    {"attack_name": "Sprinkle Spin", "base_damage": 3},
    {"attack_name": "Sugar Slice", "base_damage": 2},
    {"attack_name": "Marshmallow Melt", "base_damage": 3},
    {"attack_name": "Frost Fang", "base_damage": 4},
    {"attack_name": "Cocoa Crush", "base_damage": 4},
    {"attack_name": "Gumblin Grapple", "base_damage": 3},
    {"attack_name": "Truffle Toss", "base_damage": 3},
    {"attack_name": "Bonbon Blast", "base_damage": 3},
    {"attack_name": "Candy Cannon", "base_damage": 4},
    {"attack_name": "Mochi Munch", "base_damage": 2},
    {"attack_name": "Taffy Tackle", "base_damage": 3},
    {"attack_name": "Jelli Jump", "base_damage": 2},
    {"attack_name": "Frost Flick", "base_damage": 2},
    {"attack_name": "Cinna Crunch", "base_damage": 3},
    {"attack_name": "Mallow Munch", "base_damage": 2},
    {"attack_name": "Sour Slam", "base_damage": 3},
    {"attack_name": "Twizzle Toss", "base_damage": 2},
    {"attack_name": "Crumble Kick", "base_damage": 3},
    {"attack_name": "Snicker Strike", "base_damage": 2},
    {"attack_name": "Cocoa Kick", "base_damage": 3},
    {"attack_name": "Meringue Maul", "base_damage": 3},
    {"attack_name": "Gumdrop Drop", "base_damage": 2},
    {"attack_name": "S'more Swoop", "base_damage": 3},
    {"attack_name": "Frost Flake", "base_damage": 2},
    {"attack_name": "Pecan Punch", "base_damage": 3},
    {"attack_name": "Maple Munch", "base_damage": 2},
    {"attack_name": "Crisp Cut", "base_damage": 3},
    {"attack_name": "Cane Crush", "base_damage": 3},
    {"attack_name": "Brittle Break", "base_damage": 3},
    {"attack_name": "Fudge Flick", "base_damage": 2},
    {"attack_name": "Mochi Mash", "base_damage": 3},
    {"attack_name": "Puffer Punch", "base_damage": 3},
    {"attack_name": "Cinna Cut", "base_damage": 2},
    {"attack_name": "Syrup Slice", "base_damage": 2},
    {"attack_name": "Glaze Gust", "base_damage": 2},
    {"attack_name": "Mallow Mash", "base_damage": 3},
    {"attack_name": "Tart Tackle", "base_damage": 3},
    {"attack_name": "Crumble Crunch", "base_damage": 3},
    {"attack_name": "Jelly Jump", "base_damage": 2},
    {"attack_name": "Nougat Nudge", "base_damage": 2},
    {"attack_name": "Sprinkle Slam", "base_damage": 3},
    {"attack_name": "Sugar Slam", "base_damage": 3},
    {"attack_name": "Marshmallow Maul", "base_damage": 3},
    {"attack_name": "Frost Flare", "base_damage": 3},
    {"attack_name": "Cocoa Crash", "base_damage": 4},
    {"attack_name": "Gumcat Grapple", "base_damage": 3},
    {"attack_name": "Truffle Tumble", "base_damage": 3},
    {"attack_name": "Bonbon Bash", "base_damage": 3},
    {"attack_name": "Candy Crush", "base_damage": 4},
    {"attack_name": "Mochi Maul", "base_damage": 3},
    {"attack_name": "Taffy Toss", "base_damage": 2},
    {"attack_name": "Jelli Jolt", "base_damage": 3},
    {"attack_name": "Frost Flick", "base_damage": 2},
    {"attack_name": "Cinna Crunch", "base_damage": 3},
    {"attack_name": "Mallow Munch", "base_damage": 2},
]

def get_random_attacks(num_attacks=2):
    """Selects a number of unique random attacks from the master list."""
    # We return copies to prevent modifying the original ATTACK_LIST
    return [attack.copy() for attack in random.sample(ATTACK_LIST, num_attacks)]